version: "3.8"

# Umumiy sozlamalar (Template)
x-landing-template: &landing-template
  image: nginx:alpine
  restart: always
  deploy:
    resources:
      limits:
        cpus: "0.50"
        memory: 256M

services:
  artrowell:
    <<: *landing-template
    ports: ["3001:80"]
    volumes:
      - ./artrowell-landing.uz:/usr/share/nginx/html:ro

  cardio-balance:
    <<: *landing-template
    ports: ["3002:80"]
    volumes:
      - ./cardio-balance-landing.uz:/usr/share/nginx/html:ro

  dermozil:
    <<: *landing-template
    ports: ["3003:80"]
    volumes:
      - ./dermozil-landing.uz:/usr/share/nginx/html:ro

  diabetikforte:
    <<: *landing-template
    ports: ["3004:80"]
    volumes:
      - ./diabetikforte-landing.uz:/usr/share/nginx/html:ro

  diastop:
    <<: *landing-template
    ports: ["3005:80"]
    volumes:
      - ./diastop-landing.uz:/usr/share/nginx/html:ro

  fatality:
    <<: *landing-template
    ports: ["3006:80"]
    volumes:
      - ./fatality-landing.uz:/usr/share/nginx/html:ro

  gemo-plus:
    <<: *landing-template
    ports: ["3007:80"]
    volumes:
      - ./gemo-plus-landing.uz:/usr/share/nginx/html:ro

  gipertofort:
    <<: *landing-template
    ports: ["3008:80"]
    volumes:
      - ./gipertofort-landing.uz:/usr/share/nginx/html:ro

  parazit-off:
    <<: *landing-template
    ports: ["3009:80"]
    volumes:
      - ./parazit-off-landing.uz:/usr/share/nginx/html:ro

  slimfit:
    <<: *landing-template
    ports: ["3010:80"]
    volumes:
      - ./slimfit-landing.uz:/usr/share/nginx/html:ro

  sustaflex:
    <<: *landing-template
    ports: ["3011:80"]
    volumes:
      - ./sustaflex-landing.uz:/usr/share/nginx/html:ro

  urion:
    <<: *landing-template
    ports: ["3012:80"]
    volumes:
      - ./urion-landing.uz:/usr/share/nginx/html:ro

  uro-pro:
    <<: *landing-template
    ports: ["3013:80"]
    volumes:
      - ./uro-pro-landing.uz:/usr/share/nginx/html:ro

  visucaps:
    <<: *landing-template
    ports: ["3014:80"]
    volumes:
      - ./visucaps-landing.uz:/usr/share/nginx/html:ro
